services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:${DB_PORT:-3306}"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      interval: 1m
      timeout: 5s
      retries: 3
  app:
    build: .
    env_file:
      - ".env"
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
volumes:
  db_data:
    driver: local
